### ISSUE TITLE
exclude spring-boot-starter-web from spring-boot-starter-web-services

### ISSUE THREAD

**Issue by longqinsi** [gungor/spring-webclient-soap#1]
You need to exclude spring-boot-starter-web from spring-boot-starter-web-services in pom.xml, otherwise this will be a blocked web site instead of a reactive web site:
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by gungor** [comment]
Thanks. You are right. Actually it is blocked already. The purpose of this repository is to show an example using WebClient to call SOAP services. Result of Soap service does not return from controller.

**Comment by gungor** [comment]
actually it does not affect current behaviour since controller is not reactve. Howeever no need to starter-web. fixed
