### ISSUE TITLE
SOAP Header using WebClient

### ISSUE THREAD

**Issue by cipley** [gungor/spring-webclient-soap#5]
Hi,

I was trying to use this for my SOAP service client, and I already succeeded on calling SOAP web service.
However, some of my SOAP backends require SOAP Headers for authentication, i.e. using `Wss4jSecurityInterceptor` when using Spring Boot. Some of it have custom header implementation on their wsdl.

Is there any way to add SOAP Header in the message so we can authenticate the call while using `WebClient` for reactive SOAP calls based on your encoder/decoder?

Edit: Actually mentioned in #4 in the end of the issue description as well

**Comment by gungor** [comment]
Hi Cipley,

More people are asking about this feature. I will soon enhance request in order to handle soap header arguments.

**Comment by gungor** [comment]
Hey, I have added Soap header feature. Header content can be send to ReactiveSoapClient as String now. It is tested

**Comment by cipley** [comment]
Thank a lot! I will try as soon as I get the chance.
Question: do you have any tips on how to send headers that is integrated in the WSDL, or should we stick to sending the SOAP headers in String format?

**Comment by gungor** [comment]
One solution you can marshall header object provided by wsdl and send xml as an argument to ReactiveSoapClient. Or can you provide a github project that includes soap header in wsdl, so that I can enhance SoapEnvelopeRequest class to handle Soap header?
